modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="food_expiry_date"
version="0.0.4"
displayName="Food Expiry Date"
displayURL="https://www.curseforge.com/members/handsondigitsmods/projects"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Sekaus"
description="This mod adds an expiration date to all food items + some new ways to store food and make it last longer."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.food_expiry_date]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration